[Feat] plant_records 등록 API
gdsc-konkuk/Plantory-Server pull request #17
Opened 2024-01-15 08:59 UTC by goldentrash

인수테스트를 위해 별도 `PlantRecordAcceptanceTest`를 만들어야 할까 고민했는데, 인수테스트라면 aggregate 단위로 작성하는게 맞을거 같아서 `CompanionPlantAcceptanceTest`에 Case를 추가했습니다.

2024-01-15 11:59 UTC, zbqmgldjfh approved these changes
크게 반려할 점은 없다 생각되어 approve 남깁니다.

2024-01-15 11:59 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        value = ["/{id}/records"],
저같은 경우 사실 url 상에 사용자의 id같은 식별할 수 있는 대상을 지칠하는것을 지양하는편 이긴 한데,
이산님 의견이 궁금하네요!~~

서로 다른사용자가 v1/plants/1/records 를 동일하게 사용할 일은 없을까요?

2024-01-15 11:59 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/acceptance/CompanionPlantStep.kt
> +                .post("/api/v1/plants/${1}/records")
("/api/v1/plants/{id}/records", 1) 처럼 사용할 수 있을거에요!

2024-01-15 12:51 UTC, goldentrash commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        value = ["/{id}/records"],
저는 URL의 목적이 `resource` **식별**에 있다고 생각합니다.
그래서 URL을 흔히 **계층 구조**라고 얘기하고, 그렇게 설계한다고 생각해요.
때문에 `plants`라는 resources 아래에 특정 개체가 있고, 그 아래에 있는 `records`를 조회하는게 맞다고 생각합니다. 왜냐하면 `/plant/:id/records`에 속한 record 자원은 해당 plant에 명확하게 종속되어 있기 때문이죠.

말씀하시는 "서로 다른 사용자가 해당 record를 동일하게 사용할 일"에 대해서는, 얼마든지 있을 수 있다고 생각합니다. 저기서 명시한 id는 사용자가 아닌 `Plant`의 id인데 혼동이 있으셨던게 아닐까 싶어요

2024-01-15 13:12 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        value = ["/{id}/records"],
[카톡 대화]
url이 자원 식별의 목적인거는 맞는데, 우리가 우리를 식별하는 주민번호를 폰번같은데 안쓰는 것 처럼?
아 비유가 이상한가?
일단 단순 순차 증가하는 id같이 예상 가능한 값들로 식별하는거는 반대일세 허허허, 저부분 uuid로 바꾸면 난 OK
![image](https://github.com/gdsc-konkuk/Plantory-Server/assets/60593969/b7036746-f002-4010-9803-2bef0a8a3452)

2024-01-15 20:50 UTC, goldentrash commented
데일리 기록 조회에 `Native Query`를 통해 최적화를 하려 하였지만... 실패했습니다. 우선 자고 좀 더 생각해 봐야겠네요.

TEST 쪽에서 특히 용어(명칭) 통일이 잘 되고 있지 않다는 느낌을 받아서 프로젝트를 전체적으로 훑어보면서 조금씩 통일해뒀습니다. 가독성에 도움이 되었다고 믿지만,,, 혼자 코드짜던 시절의 안 좋은 버릇일지 리뷰랑이 너무 많아질걸 생각 못 했네요. 다음에는 조심하겠습니다.

2024-01-16 02:38 UTC, zbqmgldjfh requested changes

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
> +fun CompanionPlantRepository.findRecordByIdAndMemberIdAndDateOrThrow(
인자가 3개쯤으로 넘어가면 @Query() 사용은 어떨까요?? 메서드 이름이 솔직하게 눈에 잘 안들어옵니다 ㅠ,ㅠ 날짜로 찾는다는게 핵심이라, findByDate정도로 이름 바꾸어 @Query랑 함께 사용하면 좋을것 같아요!!

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
> +    if (records.isEmpty()) {
기록이 없는게 예외일까요? 그냥 없으면 없는 리스트를 반환해주면 될것 같아서요!!

등록해둔 식물이 없어서 예외가 발생하는 것 이랑,
그냥 애당초 없는 데이터라 empty를 반환하는것은 다르다 생각됩니다~

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
> +    return records[0]
이 0의 의미는 뭔가요??, 여러개중 하나만 반환한다는 의미인가요??
애당초 근데 기록은 하루당 하나인데, List로 조회해서 0번째를 반환하는 이유가 있나요?

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
> +//        """
사용하지 않는 쿼리 제꺼랑 함께 삭제 한번만 부탁드릴게요!!
저도 까먹고 주석해논거 안지웠네요 ㅋㅋㅋ

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
> +        get() = this.imageUrl!!.value
기존에 사용하던 ImageUrl 값객체로 혹시 변경해주실 수 있을까요?? 만들어두고 PlantRecord에서는 안쓰고 있었네요 ㅋㅋㅋ

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        "/records", consumes = [MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE]
이부분 개행해서 3줄로 만드신 이유가 있을까요? 길어서 일까요?? 보통 Mapping은 한줄에 다적긴해서요!!

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/common/support/photo/PhotoNameGeneratorTest.kt
> -    fun `이미지 파일 확장자가 아닌경우 예외 발생`(filename: String) {
수정해주신점 우선 감사합니다만, 솔직하게 "아닌경우" 와 "아니면" 차이로 의미가 크게 달라지는지 모르겠습니다??

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
> +    fun generateCompanionPlantCreateRequest(nickname: String): CompanionPlantCreateRequest {
nickName으로 바뀐 이유가?? 추가로 바뀐후 사용되는 변수가 아닌것 같아서요!

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/plant/domain/CompanionPlantTest.kt
> -    fun `기록 작성 테스트`() {
"테스트" 부분 제거해주신점 좋습니다!!

2024-01-16 02:38 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/PlantoryApplicationTests.kt
> -
사실 이 테스트는 Spring이 기본으로 하나 만들어주는 테스트라 삭제해버려도 좋습니다!!

2024-01-16 02:38 UTC, zbqmgldjfh requested changes
수고 많으셨습니다!!! 감사합니다~
일부분만 수정해주시면 될것 같아요!

2024-01-16 02:43 UTC, goldentrash commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlantRepository.kt
> +    if (records.isEmpty()) {
그러면 데일리 기록 조회 API가 List로 response하도록 API도 수정하겠습니다

2024-01-16 02:45 UTC, goldentrash commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        "/records", consumes = [MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE]
아 그렇군요. 가독성 향상을 위해서였는데 다시 한 줄로 변경해두겠습니다

2024-01-16 02:47 UTC, goldentrash commented on src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
> +    fun generateCompanionPlantCreateRequest(nickname: String): CompanionPlantCreateRequest {
```kt
// before
    @Test
    fun `반려식물 등록`() {
        // given
        val 반려_식물_정보 = generateCompanionPlantCreateRequest(1L)

        // when
        val 식물_등록_요청_응답 = 반려_식물_등록_요청(반려_식물_정보, "device-token")

        // then
        응답_확인(식물_등록_요청_응답, HttpStatus.OK)
    }
```
보다는 

```kt
// after
    @Test
    fun `반려식물 등록`() {
        // given
        val 반려_식물_정보 = generateCompanionPlantCreateRequest("퐁퐁이")

        // when
        val 식물_등록_요청_응답 = 반려_식물_등록_요청(반려_식물_정보, "device-token")

        // then
        응답_확인(식물_등록_요청_응답, HttpStatus.OK)
    }
```
가 좀 더 이해하기 읽기 편할거라 생각했습니다. 의도하신와 의미상 맞지 않다면 다시 수정해두겠습니다

2024-01-16 02:48 UTC, goldentrash commented on src/test/kotlin/gdsc/plantory/PlantoryApplicationTests.kt
> -
바로 삭제해버리겠습니다

2024-01-16 02:49 UTC, goldentrash commented on src/test/kotlin/gdsc/plantory/common/support/photo/PhotoNameGeneratorTest.kt
> -    fun `이미지 파일 확장자가 아닌경우 예외 발생`(filename: String) {
이 부분은 크게 변경할 이유는 없었던게 맞는것 같네요. 다만 이미 수정해뒀으니 롤백하지는 않겠습니다

2024-01-16 02:56 UTC, goldentrash commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        "/records", consumes = [MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE]
아 이거 인텔리로 자동 포매팅 했더니 라인 당 길이수 제한으로 자동 개행이 되네요. 특별히 아니다라고 느끼지 않으신다면 개행 유지하도록 하겠습니다

2024-01-16 03:56 UTC, goldentrash commented on src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
> +    fun generateCompanionPlantCreateRequest(nickname: String): CompanionPlantCreateRequest {
[카톡 대화]
설계된 객체의 `equals`, `hash`가 ID를 기반으로 작성되어 동등 비교를 할경우 id를 사용해야 하는 점.
따라서 id가 달라야 할 경우는 많지만 이름은 중복 여부와 전혀 관계가 없다.
롤백합니다 :)

2024-01-16 04:51 UTC, zbqmgldjfh requested changes
지금과 같이 그냥 쿼리 날려서 확인하기 보다는 이미 찾아둔 반려식물에게 물어보시죠?
도메인이 할 일을 서비스가 하고 있습니다 지금은 허허

2024-01-16 04:51 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
> +        validateDuplicatePlantRecord(request.companionPlantId, findMember.getId, LocalDate.now())
중복된 기록이 있는지는 findCompanionPlant에게 물어봐야 하지 않을까요??

2024-01-16 06:02 UTC, zbqmgldjfh requested changes
반려 드립니다 ㅋㅋㅋ 객체지향좀 생각해보자구요!!!

2024-01-16 06:02 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/common/support/photo/PhotoLocalManagerTest.kt
> +@DisplayName("통합 : PhotoLocalManager")
이게 왜 통합 테스트죠? 이거 단위 테스트 입니다만???

2024-01-16 06:25 UTC, zbqmgldjfh approved these changes
수고 많으셨습니다!

2024-01-16 06:29 UTC, merged