[Feat] plant history 조회 API
gdsc-konkuk/Plantory-Server pull request #20
Opened 2024-01-16 15:29 UTC by goldentrash

# Todo

- [x] 기록 조회 API 구현, close #19 

### Additional

- `PlantRecord`가 state 대신 behavior를 사용하도록 수정
- 인수테스트 스탭의 응답 확인 parameter 이름을 `request`에서 `response`로 수정
- `HistoryDto`, `CompanionPlantHistoryRequest` 등을 `PlantHistory...`로 이름 통일

2024-01-17 05:55 UTC, zbqmgldjfh requested changes
수고 많으셨습니다!~~
일부 부분들 수정해주시면 감사하겠습니다!!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
> +    private val histories: PlantHistories = PlantHistories()
이거 근데 이름 바뀐 이유가 있나요?  CompanionPlant 도메인의 히스토리라 당연하게 식물의 히스토리라, 약간 네이밍이 중복된 정보를 전달하는 것 같아서요!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantHistory.kt
>  @Table(name = "HISTORY")
PlantHistory로 변경하시고 싶으면 테이블 이름도 함께 변경 부탁드립니다!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
> +    fun isRegisteredAt(date: LocalDate) = LocalDate.from(this.createAt) == date
객체에게 물어보는것은 좋은데, LocalDate.from 을 사용한 이유가 있나요?
혹시 제가 LocalDate.from 를 언제 사용한것인지 고민해본적 있으실까요?

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantRecords.kt
> +    fun isAlreadyRegisteredAt(date: LocalDate) = this.plantRecords.find { it.isRegisteredAt(date) } != null
함수의 반환타입을 명시헤주시면 좋을것 같아요!
Unit 타입 외의 Query형 메서드들은 모두 반환타입을 명시해주세욥!!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/presentation/PlantCommandApi.kt
> +        @RequestBody request: PlantHistoryRequest,
네이밍을 통합하고싶다면 위의 create API 까지 함께 적용해주시면 좋을것 같아요!! 전 둘다 네이밍 어느쪽이든 상관없을것 같습니다!!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
> +    fun lookupAllHistoriesOfMonth(request: PlantHistoriesLookupRequest, deviceToken: String): List<PlantHistoryDto> {
이름 바뀐거 좋아요~!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
> +        return companionPlantRepository.findAllHistoriesByMonth(
이부분 너무 눈에 안들어오는거 같아요, 메서드로 의미좀 부여해주세요!
stream 보면서 한줄 한줄 읽는게 지금은 변환과정이 적어서 다행이긴 한데, 같이 일하는 동료에게는 잘 안읽힐 수 있어요!!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
> +        plantInformationId = TEST_PLANT_INFO_ID,
TEST_PLANT_INFO_ID의 경우 PlantFixtture에 정의 되어있을 줄 알았는데,
데이터 초기화하는 곳에 있더군요,

각자의 역할에 맞도록 책임을 할당하면 좋을것 같아요!
초기화 하는 녀석은 초기화만,
Fixture를 만드는 놈은 픽스쳐와 상수들만!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
> +const val TEST_MEMBER_ID = 1L
이거 Fixture 쪽으로 아예 이동시켜도 좋을것 같아요!!

식물 만드는 부분들도 기존의 Fixture 사용해도 좋을것 같아요!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantHistory.kt
> +    val getDate: LocalDate
이부분을 보니 제가 LocalDate.from 을 사용한 의도를 모르셨다 생각됩니다!
바로 알려드릴수도 있는데, 그보단 먼저 생각해보신후 남겨주세요!!

2024-01-17 05:55 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/service/PlantService.kt
> +        return companionPlantRepository.findAllByMemberId(findMember.getId)
저라면 이부분 메서드로 뽑아서 의미를 전달했을것 같습니다!
팀원에게 구현을 보게하기 보다는, 의미를 전달하려 노력해주세요!

2024-01-17 08:18 UTC, goldentrash commented
`LocalDate.from()` 부분은 위에 코멘트로 달아 뒀습니다. 추가 피드백 부탁드려요

2024-01-17 08:21 UTC, goldentrash commented on src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
> +                CompanionPlantFixture.generateTestCompanionPlantWithHistories(),
이 부분을 아래와 같이 순서를 변경하면 DB 초기화가 제대로 되지 않는데 이유가 무엇일까요? JPA 영속 컨텍스트 문제 같은데, `CompanionPlant`의 동일 체크에 사용되는게 id라 이유를 잘 모르겠습니다.

```kt
        companionPlantRepository.saveAll(
            listOf(
                CompanionPlantFixture.generateTestCompanionPlantWithHistories(),
                CompanionPlantFixture.generateTestCompanionPlantWithoutHistories(),
            )
        )
```

다음은 TEST 로그 중 일부입니다.

![image](https://github.com/gdsc-konkuk/Plantory-Server/assets/33625132/7168a559-50da-4b92-897e-1d47667e4a32)

`generateTestCompanionPlantWithoutHistories`로 생성된 반려식물을 **추가하는게 아닌 기존 식물을 갱신**하고 있습니다.

2024-01-17 08:35 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantHistory.kt
> +    val getDate: LocalDate
다음 테스트에 대하여 고민해보시죠!
```
    @Test
    fun test() {
        // given
        val companionPlant: CompanionPlant = CompanionPlantFixture.덕구리난
        val birthDate = companionPlant.getBirthDate

        // when
        companionPlant.getBirthDate.plusDays(1)

        // then
        assertThat(companionPlant.getBirthDate).isEqualTo(birthDate)
    }
```

2024-01-17 08:36 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
> +    fun isRegisteredAt(date: LocalDate) = LocalDate.from(this.createAt) == date
위에서 동일성 비교(주소값)보다 동등성 비교(실제 값의 비교)를 하는것이 더 좋다 생각됩니다.
일반적으로 동등성 비교는 equals를 사용하는것이 통용적이라 생각됩니다.

2024-01-17 08:36 UTC, zbqmgldjfh commented on src/main/kotlin/gdsc/plantory/plant/domain/CompanionPlant.kt
> +    private val histories: PlantHistories = PlantHistories()
사실 제 생각에는 PlantRecord를 Record로 바꾸는게 좋을거 같다 생각하기는 하는데, 어느 쪽이든 크게 상관없을것 같아요!!

2024-01-17 08:54 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/util/DatabaseLoader.kt
> +                CompanionPlantFixture.generateTestCompanionPlantWithHistories(),
일단 transaction도 없는 영역에서 수정해봐도 의미 없습니다~
<img width="893" alt="image" src="https://github.com/gdsc-konkuk/Plantory-Server/assets/60593969/2972e9b2-7c36-4160-ae77-74ae088a6e87">
애당 영속성 컨텍스트에 들어간적도 없는 녀석들에 연산을 가하시고 있어여~

히스토리 생성 선후 관계 생각해보면 도움 될듯요!~

근데 애당초 Fixture에서 너무 많은 일을 하고 있어요...
그냥 객체를 생성만 해야 Fixture이지... 너무 많은 일을 하고 있습니다...

2024-01-17 14:49 UTC, goldentrash commented on src/main/kotlin/gdsc/plantory/plant/domain/PlantRecord.kt
> +    fun isRegisteredAt(date: LocalDate) = LocalDate.from(this.createAt) == date
[카톡 대화]

kotlin은 java와 다르게 `==`연산에 내부적으로 `equals`를 수행

2024-01-18 01:36 UTC, zbqmgldjfh approved these changes
approve 남겼습니다만,,, id 상수부분... 음...

2024-01-18 01:36 UTC, zbqmgldjfh commented on src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
> +val 기록없는_테스트식물_ID
이거 거의 마술 수준이라, 다른 동료가 보면 뭐하는건지 좀 살펴봐야 알 수 있을거 같아요,
밑에쪽을 보니 식물만들때 id를 받아 할당하고 get으로 호출하는데......

그럼 A라는 식물 id1로 만들고 B라는 식물 id2로 만들고 get하면 어떻게 되나요??

이쯤 되면 그냥 상수 안만드는게 좋을거 같기도 합니다

2024-01-18 02:02 UTC, goldentrash commented on src/test/kotlin/gdsc/plantory/fixture/CompanionPlantFixture.kt
> +val 기록없는_테스트식물_ID
확실히 말씀하신 내용에 공감합니다. 제가 위에서 발생한 JPA id 생성 전략을 이해하지 못하고 있을 때 구상하기 시작한 상수화여서 해당 내용을 수정해 나가다 보니 꼬이기 시작하더라고요.

현 PR은 원래 의도와 다르게 너무 오래 진행된 느낌이 강하니, approve 해주신대로 우선 머지하고, 추후 리팩토링을 하도록 하겠습니다.

2024-01-18 02:02 UTC, merged